<a href="https://colab.research.google.com/github/Chirag-R-Karanth/Code/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- core library for scientific and numerical computing in python
- linear algebra, Fourier Transform
- provides high performance multidimensional array object and tools for working with arrays
- main object  is the multidimensional array
- t is a table of elements (usually numbers) , of same data type, indexed by a tuple of positive integers
- dimensions = axes
- numpy arrays aka ND arrays

### Why Numpy and not lists?
- Fast - have been optimized for years and thus implementation is quick
- Convienient - has different libraries from python lists and more no. of functionalities
- Less Memory

In [ ]:
#import numpy as np
import numpy

ar=numpy.array([1,2,3])
print(ar)
print(type(ar))

# l=[1,2,3]
# print(l)
# print(type(l))


[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([])
print(a)
print(type(a))

c=3.4
print(type(c))

[]
<class 'numpy.ndarray'>
<class 'float'>


In [ ]:
b = np.array([1,2,3,4])
print(b)
print(type(b))



[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
b=np.array(['a',"b",'c',"d"])
print(b)
print(type(b))

['a' 'b' 'c' 'd']
<class 'numpy.ndarray'>


In [ ]:
#c=np.array([1,2.2,3,4.4,5,6])
c=np.array(["a","v","g", 1,2,3])
print(c)
print(type(c))

['a' 'v' 'g' '1' '2' '3']
<class 'numpy.ndarray'>


In [ ]:

print("\n Dtype : " , c.dtype)
print("\n NDim : " , c.ndim) # Dimensions of numpy array
print("\n ItemSize : " , c.itemsize) # size of a single element in the numpy array

#Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving
#the size of the array along each dimension.

print("\n Shape : " , c.shape)
print("\n NBytes : " , c.nbytes)


 Dtype :  <U21

 NDim :  1

 ItemSize :  84

 Shape :  (6,)

 NBytes :  504


In [ ]:
c=np.array([1,2,3.5,4,5.7,7.8])
print(c)
print(type(c))
print("\n Dtype : " , c.dtype)
print("\n NDim : " , c.ndim) # Dimensions of numpy array
print("\n ItemSize : " , c.itemsize) # size of a single element in the numpy array

#Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving
#the size of the array along each dimension.

print("\n Shape : " , c.shape)
print("\n NBytes : " , c.nbytes)

[1.  2.  3.5 4.  5.7 7.8]
<class 'numpy.ndarray'>

 Dtype :  float64

 NDim :  1

 ItemSize :  8

 Shape :  (6,)

 NBytes :  48


In [ ]:
c=np.array([1,2,5.7,7.8])
print(c)
print(type(c))
print("\n Dtype : " , c.dtype)
print("\n NDim : " , c.ndim) # Dimensions of numpy array
print("\n ItemSize : " , c.itemsize) # size of a single element in the numpy array

#Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving
#the size of the array along each dimension.

print("\n Shape : " , c.shape)
print("\n NBytes : " , c.nbytes)

[1.  2.  5.7 7.8]
<class 'numpy.ndarray'>

 Dtype :  float64

 NDim :  1

 ItemSize :  8

 Shape :  (4,)

 NBytes :  32


### Checking Version of Numpy

In [ ]:
print(np.__version__)

2.0.2


## Creating Numpy Arrays

This is a TEXT

In [ ]:
#a=np.array([[row1],[row2],[row3]])
#print("\n NDim : " , a.ndim)

a=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [ ]:
# 2D array
a=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[3,6,8,2]])
print(a)


[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 8]
 [3 6 8 2]]


In [ ]:
# exercise write a code to make a 4*2 matrix


In [ ]:
numpy_array = np.array([[1,3,3], [3,4,1], [5,6,2]])

print("\n A numpy array: \n" , numpy_array)
print("\n Type : ", type(numpy_array))
print("\n Dtype : " , numpy_array.dtype)
print("\n NDim : " , numpy_array.ndim) # Dimensions of numpy array
print("\n ItemSize : " , numpy_array.itemsize) # size of a single element in the numpy array

#Shape of numpy array in (rows,columns)the shape of an array is a tuple of integers giving
#the size of the array along each dimension.

print("\n Shape : " , numpy_array.shape)
print("\n NBytes : " , numpy_array.nbytes)


 A numpy array: 
 [[1 3 3]
 [3 4 1]
 [5 6 2]]

 Type :  <class 'numpy.ndarray'>

 Dtype :  int64

 NDim :  2

 ItemSize :  8

 Shape :  (3, 3)

 NBytes :  72


In [ ]:
a=np.array(['a','b','c','d','e'])
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.nbytes)

['a' 'b' 'c' 'd' 'e']
<U1
1
(5,)
4
20


In [ ]:
a=np.array([['abc','bgb'],['cyu','djk'],['yub','rty']])
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.nbytes)

[['abc' 'bgb']
 ['cyu' 'djk']
 ['yub' 'rty']]
<U3
2
(3, 2)
12
72


# Exercise

In [ ]:
# exercise

numpy_array = np.array([[1,2,3,4], [5,6,7,8]])

#Find

print("\n Type : ", type(numpy_array))
print("\n Dtype : " , numpy_array.dtype)
print("\n NDim : " , numpy_array.ndim) # Dimensions of numpy array
print("\n ItemSize : " , numpy_array.itemsize) # size of a single element in the numpy array

print("\n Shape : " , numpy_array.shape)
print("\n NBytes : " , numpy_array.nbytes)


 Type :  <class 'numpy.ndarray'>

 Dtype :  int64

 NDim :  2

 ItemSize :  8

 Shape :  (2, 4)

 NBytes :  64


In [ ]:
# TypeCasting
b = 8
print(b)
print(type(b))

c = float(b)
print(type(c))
print(c)



8
<class 'int'>
<class 'float'>
8.0


In [ ]:
#Typecasting of numpy arrays
arr_fl = np.array([[1,2], [3,4], [5,6]])
print( arr_fl)
print(arr_fl.dtype)


arr_fl = np.array([[1,2], [3,4], [5,6]] , dtype = np.float16)
print(" A Float Array: \n" , arr_fl)
print(arr_fl.dtype)



[[1 2]
 [3 4]
 [5 6]]
int64
 A Float Array: 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
float16


In [ ]:
## can you predict the answer
arr = np.array([[1.1,2.2], [3.5,4.6], [5.2,6.1]])
print(arr)
print(arr.dtype)

arr1 = np.array(arr , dtype = np.int16)
print(" \nInteger Array: \n" , arr1)
print(arr1.dtype)

[[1.1 2.2]
 [3.5 4.6]
 [5.2 6.1]]
float64
 
Integer Array: 
 [[1 2]
 [3 4]
 [5 6]]
int16


In [ ]:
arr_comp = np.array([[1.1,2.2], [3.5,4.6], [5.2,6.1]] , dtype = np.str_)
print(arr_comp)
print(arr_comp.dtype)

[['1.1' '2.2']
 ['3.5' '4.6']
 ['5.2' '6.1']]
<U3


In [ ]:
arr_comp = np.array([['1.1','2.2'], ['3.5','4.6'], ['5.2','6.1']] , dtype = np.float16)
print(arr_comp)
print(arr_comp.dtype)

[[1.1 2.2]
 [3.5 4.6]
 [5.2 6.1]]
float16


In [ ]:
# arr_comp = np.array([['1.1','2.2'], ['3.5','4.6'], ['5.2','6.1']] , dtype = np.int64)
# print(arr_comp)
# print(arr_comp.dtype)

In [ ]:
# Initialize all the elements of the numpy array with 0
zero_array = np.zeros((4,6), dtype=np.int64)
print(zero_array)
print(zero_array.dtype)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
int64


In [ ]:
# Initialize all the elements of the numpy array with 1
ones_array = np.ones((4,4))
print(ones_array)
print(ones_array.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [ ]:
#Array filled with
full_array = np.full((4,7), 5)
print(full_array)
print(full_array.dtype)

[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]
int64


In [ ]:
# Exercise

# make a 6*7 array having all 0
# make a 3*8 array having all 1
# make a 5*3 array having all 7



In [ ]:
z=np.zeros((6,7))
print(z)
print("\n")

o=np.ones((3,8))
print(o)
print("\n")

f=np.full((5,3),7)
print(f)
print("\n")

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]




In [ ]:
#Array with arange() function

A = np.arange(10)
print( A)
print(type(A))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
b=np.arange(3,20)
print(b)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:

arange_array = np.arange(4, 30, 5)

print(arange_array)

[ 4  9 14 19 24 29]


In [ ]:
# Exercise

# write a code to print [ 3  6  9 12 15 18 21 24 27]



[ 3  6  9 12 15 18 21 24 27]


In [ ]:
#print odd nos ranging from 0-50
print(np.arange(1,50,2))


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [ ]:
# A 3x3 array of random values uniformly distributed between 0 and 1

ran_arr = np.random.random((2,3))
print(ran_arr)

[[0.43983511 0.35161226 0.94476065]
 [0.45930179 0.87883517 0.96748916]]


In [ ]:
# A 3x4 array of random integers

a=np.random.randint(1, 7, (3, 4))
print(a)


[[4 3 2 2]
 [2 3 5 1]
 [2 3 1 6]]


In [ ]:
# Exercise

# make a 4*5 array of random integers in the interval [5,15]

np.random.randint(5, 16, (4, 5))

array([[13,  9,  7,  8, 15],
       [14, 11, 13, 13,  5],
       [12, 11,  7, 14,  6],
       [14, 10,  9,  7, 13]])

# Array Manipulation

### Array Indexing : Accessing Single Elements


In [ ]:
# In one-dimensional array
arr1 = np.arange(4,15)
print('Array:\n' , arr1)

Array:
 [ 4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
#Accessing the data
print(arr1[0])
print(arr1[3])
print(arr1[5])
print(arr1[-1])
print(arr1[-4])

4
7
9
14
11


In [ ]:
#In Multidimensional Array
arr2=np.array([[2,3,4],[5,6,7],[4,7,8]])
print(arr2)
print(arr2[0,1])
print(arr2[1,2])
print(arr2[2,2])


[[2 3 4]
 [5 6 7]
 [4 7 8]]
3
7
8


In [ ]:
import numpy as np
print(arr2[0,-2])

3


In [ ]:
# Exercise

# write a code to Print 5
print(arr2[-2,-3])

5


In [ ]:
# Modifying values

print(arr2)
arr2[0,0] = 20
arr2[2,1] = 34
print("After modifiction:\n",arr2)


[[2 3 4]
 [5 6 7]
 [4 7 8]]
After modifiction:
 [[20  3  4]
 [ 5  6  7]
 [ 4 34  8]]


### Array Slicing : Accessing Subarrays

In [ ]:
# One-dimensional array
arr1 = np.arange(4,15)
print(arr1)

print(arr1[ : ])
print(arr1[1:5])
print(arr1[ : 6])
print(arr1[3:])



[ 4  5  6  7  8  9 10 11 12 13 14]
[ 4  5  6  7  8  9 10 11 12 13 14]
[5 6 7 8]
[4 5 6 7 8 9]
[ 7  8  9 10 11 12 13 14]


In [ ]:
#Two-Dimensional Array

arr2=np.array([[2,3,4],[5,6,7],[4,7,8]])
print(arr2)
print('\n arr2[[ : 2, : 3] :\n',arr2[:2, :3]) #2 rows, 3cols

#arr[row slice, col slice]
#print('\n')
#print(arr2[:2, :2]) #2 rows and 2 cols




[[2 3 4]
 [5 6 7]
 [4 7 8]]

 arr2[[ : 2, : 3] :
 [[2 3 4]
 [5 6 7]]


In [ ]:

print(arr2[1:2,1:3])

[[6 7]]


In [ ]:
print(arr2)
print('\n arr2[ : 3, : : 2] :\n',arr2[:3, ::2]) #allrows, 2 cols with a gap

[[2 3 4]
 [5 6 7]
 [4 7 8]]

 arr2[ : 3, : : 2] :
 [[2 4]
 [5 7]
 [4 8]]


In [ ]:
arr3=np.array([[1,2,3,4,5],[3,4,6,7,8],[4,7,9,2,3],[4,3,7,8,2],[7,3,4,5,2]])
print (arr3)
print('\n')
print(arr3[0:2,0:5])
print('\n')
print(arr3[:2,:])

print('\n')
print(arr3[:,: : 2])

[[1 2 3 4 5]
 [3 4 6 7 8]
 [4 7 9 2 3]
 [4 3 7 8 2]
 [7 3 4 5 2]]


[[1 2 3 4 5]
 [3 4 6 7 8]]


[[1 2 3 4 5]
 [3 4 6 7 8]]


[[1 3 5]
 [3 6 8]
 [4 9 3]
 [4 7 2]
 [7 4 2]]


In [ ]:
print(arr3)
print('\n')
print(arr3[: :3,:])

[[1 2 3 4 5]
 [3 4 6 7 8]
 [4 7 9 2 3]
 [4 3 7 8 2]
 [7 3 4 5 2]]


[[1 2 3 4 5]
 [4 3 7 8 2]]


In [ ]:
print(arr3)
print('\n')
print(arr3[: :2,: :2])

[[1 2 3 4 5]
 [3 4 6 7 8]
 [4 7 9 2 3]
 [4 3 7 8 2]
 [7 3 4 5 2]]


[[1 3 5]
 [4 9 3]
 [7 4 2]]


In [ ]:
# Exercise
print('\n arr3[ : , 1 : ] :\n',arr3[:, 1:])


 arr3[ : , 1 : ] :
 [[2 3 4 5]
 [4 6 7 8]
 [7 9 2 3]
 [3 7 8 2]
 [3 4 5 2]]


In [ ]:
print(arr2[:,0:1])

[[2]
 [5]
 [4]]


In [ ]:
print("Original array : \n" , arr2)
sub_arr2 = arr2[:2, :2]
print("Sub Array : arr2[:2, :2] \n" , sub_arr2)
sub_arr2[0, 0] = 99
print("Modified Sub Array : \n" , sub_arr2)

Original array : 
 [[2 3 4]
 [5 6 7]
 [4 7 8]]
Sub Array : arr2[:2, :2] 
 [[2 3]
 [5 6]]
Modified Sub Array : 
 [[99  3]
 [ 5  6]]


# Reshaping Array
- the size of the initial array must match the size of the reshaped array

# Reshaping

In [ ]:
array = np.arange(1,10)
print("Array originally: " , array)
print(array.ndim)
print('\n')

ar_res = array.reshape(3,3)
print('Reshaped Array:\n' , ar_res)
print(ar_res.ndim)

Array originally:  [1 2 3 4 5 6 7 8 9]
1


Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
array = np.arange(1,13)
print("Array originally: " , array)
print(array.ndim)
print('\n')
ar_res = array.reshape(6,2)
print('Reshaped Array:\n' , ar_res)
print(ar_res.ndim)

Array originally:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
1


Reshaped Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
2


In [ ]:
trans_arr = np.transpose(ar_res)
print('Transpose of Array:\n' , trans_arr)


Transpose of Array:
 [[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


In [ ]:
a=np.arange(12,24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
print('reshape(2,6)- \n', np.arange(12,24).reshape(4,3))


reshape(2,6)- 
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
# no. of arrays, no. of rows, no. of columns
print('reshape(2,3,2)- \n',np.arange(12,24).reshape(3,2,2))

reshape(2,3,2)- 
 [[[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


In [ ]:
# try making 3 arrays out of 12 values
a=np.arange(0,12)
print(a)
b=a.reshape(2,3,2)
print(b)
#print('reshape(2,2,3)- \n',np.arange(0,13).reshape(2,3,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [ ]:
# Exercise
# np.arrange(0,20)
# make one array of dimension 2 and size 4*5

# Numpy Arithmetic Operations

In [ ]:
a = np.array([[1, 2 ,3],[6,4,8],[6,8,3]])
print(a)


[[1 2 3]
 [6 4 8]
 [6 8 3]]


In [ ]:
b = np.array([10,11,12])
print(b)
#print(b.ndim)

[10 11 12]


In [ ]:

c = np.array([[3, 4 ,5],[6,7,8],[1,2,3]])
print(c)


[[3 4 5]
 [6 7 8]
 [1 2 3]]


In [ ]:
print(a)
print('\n')
print(c)
print('\n Addition \n')
print(np.add(a,c))

print('\n Subtraction \n')
print(np.subtract(a,c))

print('\n Multiplication \n')
print(np.multiply(a,c))

print('\n Division\n')
print(np.divide(a,c))

[[1 2 3]
 [6 4 8]
 [6 8 3]]


[[3 4 5]
 [6 7 8]
 [1 2 3]]

 Addition 

[[ 4  6  8]
 [12 11 16]
 [ 7 10  6]]

 Subtraction 

[[-2 -2 -2]
 [ 0 -3  0]
 [ 5  6  0]]

 Multiplication 

[[ 3  8 15]
 [36 28 64]
 [ 6 16  9]]

 Division

[[0.33333333 0.5        0.6       ]
 [1.         0.57142857 1.        ]
 [6.         4.         1.        ]]


In [ ]:
print(a)
print('\n')

print(b)
print('\n')
f=np.add(a,b)
print(f)

[[1 2 3]
 [6 4 8]
 [6 8 3]]


[10 11 12]


[[11 13 15]
 [16 15 20]
 [16 19 15]]


In [ ]:
print(np.subtract(a,c))


[[-2 -2 -2]
 [ 0 -3  0]
 [ 5  6  0]]


In [ ]:
print(np.subtract(a,b))

[[-9 -9 -9]
 [-4 -7 -4]
 [-4 -3 -9]]


In [ ]:
print(a)
print('\n')
print(b)
print('\n')
print(np.multiply(a,b))
print('\n')
print(c)
print('\n')
print(np.multiply(a,c))

[[1 2 3]
 [6 4 8]
 [6 8 3]]


[10 11 12]


[[10 22 36]
 [60 44 96]
 [60 88 36]]


[[3 4 5]
 [6 7 8]
 [1 2 3]]


[[ 3  8 15]
 [36 28 64]
 [ 6 16  9]]


In [ ]:
print(np.divide(a,b))

[[0.1        0.18181818 0.25      ]
 [0.6        0.36363636 0.66666667]
 [0.6        0.72727273 0.25      ]]


##### Iteration over array

In [ ]:
a = np.arange(0, 45, 5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [ ]:
a = a.reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [ ]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


In [ ]:
print(a)
#printing row wise
for x in np.nditer(a, order = 'C'):
    print(x)

# printing column wise
print('\n')
for x in np.nditer(a, order = 'F'):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40


0
15
30
5
20
35
10
25
40


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.array([5,6,7])
print(a)
print('\n')
print(b)
print('\n')

c=np.multiply(a,b)
print('\n')
print(c)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


[5 6 7]




[[ 5 12 21]
 [15 24 35]
 [25 36 49]]
